### ISSUE TITLE
Windows下选助理出的图片是白的

### ISSUE THREAD

**Issue by niucattle** [hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu#2]
![8(NH}4~`MHWKGYAGT8GMJN](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/0d71b3fe-0d5c-4878-b220-8eecea6d8bb8)
![$1D$3WQ_0JU@ VWR91NML_E](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/130eb8e5-dc04-42e7-8fef-7c00608a3c7f)
两个都是新兔兔，这两个月装了好多次兔兔，四个环境，在三个windows环境中，出的图全都是白的，而在ubuntu的环境中，并没有这种问题。没有报错，一切正常，我去文件夹里看图片也是正常的，但发出来的就是白的
![image](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/a9ea7d4b-6544-40e6-9c97-87da18b3b8e3)

**Comment by hsyhhssyy** [comment]
插件商店更新了一个1.5新版，你试一下有没有解决你的问题。

**Comment by niucattle** [comment]
![OTJIEWZ%}(I%PNZVUZDJ4 H](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/31ab94d8-aaf7-482f-8659-3b6267644606)
![image](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/e6ea1ed5-1b3b-461a-8943-1090d286407c)
![}IDHN1E`C 3ZW)XFV({ODGN](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/649dc5a1-779f-4975-9949-fe4a2534fe8c)

**Comment by niucattle** [comment]
我ubuntu也就是个2h4g的机子，windows上一次是8h16g的，另一次是10h64g的，现在阿米娅2号在e52666v3打了鸡血后的机子上，内存64g，显卡2080，应该性能没啥问题

**Comment by niucattle** [comment]
> 我ubuntu也就是个2h4g的机子，windows上一次是8h16g的，另一次是10h64g的，现在阿米娅2号在e52666v3打了鸡血后的机子上，内存64g，显卡2080，应该性能没啥问题

但这两个机子上都会发白图片

**Comment by niucattle** [comment]
> > 我ubuntu也就是个2h4g的机子，windows上一次是8h16g的，另一次是10h64g的，现在阿米娅2号在e52666v3打了鸡血后的机子上，内存64g，显卡2080，应该性能没啥问题
> 
> 但这两个机子上都会发白图片

ubuntu那个机子上不会

**Comment by hsyhhssyy** [comment]
升级了1.5版本以后，还是有白图吗？

**Comment by hsyhhssyy** [comment]
1.5的这个问题不一定是因为你机器卡，相反，也可能是因为你机器太快了。
它的问题是，playwright没有等网页渲染完成，就把网页图发出去了。

**Comment by niucattle** [comment]
还是白的

**Comment by niucattle** [comment]
> 还是白的

上边的图就是更新后的

**Comment by hsyhhssyy** [comment]
emm，这太难定位问题了，而且我也没有windows部署的兔兔
不过我撤回了1.5版本，因为我发现了另一个bug。

回头我加一个配置项，让他可以直接发原图而不是发html好了。

我问一个问题啊，其他的依赖复杂html的功能，比如公招识别，在你这里正常吗？

**Comment by niucattle** [comment]
> emm，这太难定位问题了，而且我也没有windows部署的兔兔 不过我撤回了1.5版本，因为我发现了另一个bug。
> 
> 回头我加一个配置项，让他可以直接发原图而不是发html好了。
> 
> 我问一个问题啊，其他的依赖复杂html的功能，比如公招识别，在你这里正常吗？

正常 其他一切正常

**Comment by niucattle** [comment]
> > emm，这太难定位问题了，而且我也没有windows部署的兔兔 不过我撤回了1.5版本，因为我发现了另一个bug。
> > 回头我加一个配置项，让他可以直接发原图而不是发html好了。
> > 我问一个问题啊，其他的依赖复杂html的功能，比如公招识别，在你这里正常吗？
> 
> 正常 其他一切正常

我也在vmware虚拟机里用纯净的windows10完全从头到尾部署一遍，结果依然是白的
详见https://www.bilibili.com/video/BV1mu411K7Wb/?spm_id_from=333.999.0.0&vd_source=f9505695b57051a3dde04f600fda6a12  的13:05

**Comment by hsyhhssyy** [comment]
那么，1.6版本还白吗？

**Comment by niucattle** [comment]
> 那么，1.6版本还白吗？

还是白的  另一个人用的arm  windows系统，也是白的

**Comment by hsyhhssyy** [comment]
![image](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/5977110/396c442f-ed18-4136-9274-9cd9ae6953b5)

那你可以帮忙做个实验吗？因为我没有windows部署的兔兔，你在插件里的wifu.html里，在如图这个位置打上`{{data.image}}`，然后看一下选助理出来白图里有那个路径没有。
看一下是Chrome渲染问题，还是路径问题啥的。

**Comment by niucattle** [comment]
> ![image](https://private-user-images.githubusercontent.com/5977110/285642546-396c442f-ed18-4136-9274-9cd9ae6953b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTYxMjMsIm5iZiI6MTcwMDk5NTgyMywicGF0aCI6Ii81OTc3MTEwLzI4NTY0MjU0Ni0zOTZjNDQyZi1lZDE4LTQxMzYtOTI3NC05Y2Q5YWU2OTUzYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjZUMTA1MDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGZmZTNkY2VlNDgyZTBkOTNmNTk4YjUyYzlkMTMwY2RkOWUxMWMyN2IxOTA0ZDRiMzdkODRjNWM1M2EzZjIxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T0CQnrj_QqziGNSuebk423DI0HZi6eWyoOdy4e1orNQ)
> 
> 那你可以帮忙做个实验吗？因为我没有windows部署的兔兔，你在插件里的wifu.html里，在如图这个位置打上`{{data.image}}`，然后看一下选助理出来白图里有那个路径没有。 看一下是Chrome渲染问题，还是路径问题啥的。

![V %3PTAQ XL EB6M@)A3XA](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/2e84145d-e2de-4840-90e8-2267ea3a18c9)

**Comment by niucattle** [comment]
![EIINFRY%TYB135TRCV2X3P9](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/a01438c5-ece4-42b4-a9cc-9f6043b378ae)

**Comment by niucattle** [comment]
![(A62$8`G26T S`5K1ZR($UC](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/dc531274-7bf1-4865-aad3-682b9b90d1b2)

**Comment by hsyhhssyy** [comment]
@niucattle 新版本1.6.1你再看一下，我大概猜到原因了。

**Comment by niucattle** [comment]
有了
![6JT)U$@3CGNRG{1T~NFR P1](https://github.com/hsyhhssyy/amiyabot-arknights-hsyhhssyy-wifu/assets/118875129/8972c30f-bbf8-4e0e-87de-10a5ecdd5497)

**Comment by hsyhhssyy** [comment]
大概是因为windows和linux路径格式不一样导致的，解决了就好。
